#!/usr/bin/env python3
"""
Prove the CV part is wired correctly WITHOUT the car, camera or drivetrain.

A previous attempt at this project crashed `manage.py drive` on launch, so the
integration is checked on its own before any autonomous logic is trusted. This
script builds a throwaway car directory from the real cv_control template with
MOCK camera / drivetrain / controller, then runs the actual vehicle loop twice:

  1. in "user" mode  -- the CV part must NOT run at all (manual drive is safe)
  2. in "local" mode -- the CV part MUST run and produce outputs

It catches import errors, wrong run() signatures, bad V.add() wiring and missing
config keys -- which is most of what makes a car fail to launch.

Usage:
    python scripts/preflight_lane_following.py
    python scripts/preflight_lane_following.py --controller LaneFollowingController
    python scripts/preflight_lane_following.py --keep   # leave the temp dir

Exit code 0 means the wiring is sound. This does not and cannot test the camera
or the CV logic itself -- for the camera see scripts/oakd_color_check.py.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
TEMPLATES = os.path.join(REPO_ROOT, "donkeycar", "templates")

MYCONFIG = """\
# Generated by scripts/preflight_lane_following.py -- MOCK everything.
CAMERA_TYPE = "MOCK"
DRIVE_TRAIN_TYPE = "MOCK"
CONTROLLER_TYPE = "mock"
USE_JOYSTICK_AS_DEFAULT = False
USE_SSD1306_128_32 = False
HAVE_ODOM = False
MAX_LOOPS = {loops}
DRIVE_LOOP_HZ = 40
WEB_CONTROL_PORT = {web_port}
WEB_INIT_MODE = "{init_mode}"
CV_CONTROLLER_CLASS = "{controller}"
LANE_WEB_ENABLE = {web_enable}
LANE_WEB_PORT = {lane_port}
DEBUG_OVERLAY = {debug}
"""


def build_car_dir(car_dir, controller, init_mode, loops, web_port, options):
    os.makedirs(car_dir, exist_ok=True)
    shutil.copy(os.path.join(TEMPLATES, "cv_control.py"),
                os.path.join(car_dir, "manage.py"))
    shutil.copy(os.path.join(TEMPLATES, "cfg_cv_control.py"),
                os.path.join(car_dir, "config.py"))
    with open(os.path.join(car_dir, "myconfig.py"), "w", encoding="utf-8") as handle:
        handle.write(MYCONFIG.format(
            controller=controller, init_mode=init_mode, loops=loops,
            web_port=web_port, web_enable=options["web_enable"],
            lane_port=options["lane_port"], debug=options["debug"]))


def run_loop(car_dir, loops):
    """Run `manage.py drive` in car_dir. Returns (exit_code, combined_output)."""
    env = dict(os.environ)
    # Make sure the loop imports THIS repo, not some other installed donkeycar.
    env["PYTHONPATH"] = REPO_ROOT + os.pathsep + env.get("PYTHONPATH", "")
    result = subprocess.run(
        [sys.executable, "manage.py", "drive"],
        cwd=car_dir, env=env, capture_output=True, text=True, timeout=180,
    )
    return result.returncode, result.stdout + result.stderr


def check(car_dir, controller, init_mode, loops, web_port, expect_cv_ran,
          options):
    label = f'{init_mode!r} mode'
    extra = " (web page on)" if options["web_enable"] else ""
    print(f"--- {label}{extra}: expecting the CV part to "
          f"{'RUN' if expect_cv_ran else 'STAY IDLE'} ---")

    build_car_dir(car_dir, controller, init_mode, loops, web_port, options)
    code, output = run_loop(car_dir, loops)

    failures = []
    if code != 0:
        failures.append(f"manage.py exited {code}")
    if "Traceback" in output:
        failures.append("a traceback appeared in the output")
    if not re.search(rf"executed {loops} steps", output):
        failures.append(f"the loop did not complete {loops} steps")
    if f"Adding part {controller}" not in output:
        failures.append(f"{controller} was never added to the vehicle")
    if options["web_enable"]:
        if "Adding part LaneFollowingWebServer" not in output:
            failures.append("the toggle web server was never added")
        if "serving on port" not in output:
            failures.append("the toggle web server never started listening")

    # The profile summary at shutdown lists only parts that actually ran.
    profiled = re.search(rf"^\|\s*{re.escape(controller)}\s*\|", output, re.MULTILINE)
    if expect_cv_ran and not profiled:
        failures.append(f"{controller} never executed (run_pilot never became true)")
    if not expect_cv_ran and profiled:
        failures.append(
            f"{controller} EXECUTED in user mode -- run_condition is not working, "
            "so the CV part can interfere with manual driving"
        )

    if failures:
        print(f"FAIL ({label}):")
        for failure in failures:
            print(f"  - {failure}")
        print()
        print("--- last 40 lines of output ---")
        print("\n".join(output.splitlines()[-40:]))
        return False

    print(f"PASS ({label})")
    return True


def main(controller, loops, keep, web_port, options):
    print(f"repo       : {REPO_ROOT}")
    print(f"python     : {sys.executable}")
    print(f"controller : {controller}")
    print()

    workdir = tempfile.mkdtemp(prefix="donkey_preflight_")
    try:
        ok = check(os.path.join(workdir, "user_mode"), controller, "user",
                   loops, web_port, expect_cv_ran=False, options=options)
        print()
        ok = check(os.path.join(workdir, "local_mode"), controller, "local",
                   loops, web_port + 1, expect_cv_ran=True,
                   options=dict(options, lane_port=options["lane_port"] + 1)) and ok

        print()
        if ok:
            print("PRE-FLIGHT PASSED -- the part is wired correctly and cannot")
            print("interfere with manual driving. Safe to try on the car.")
        else:
            print("PRE-FLIGHT FAILED -- fix this before running on the car.")
        return 0 if ok else 1
    finally:
        if keep:
            print(f"\ntemp dir kept at {workdir}")
        else:
            shutil.rmtree(workdir, ignore_errors=True)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--controller", default="PassThroughController",
                        help="CV_CONTROLLER_CLASS to exercise")
    parser.add_argument("--loops", type=int, default=100,
                        help="vehicle loop iterations per run")
    parser.add_argument("--web-port", type=int, default=8897,
                        help="port for the throwaway web controller")
    parser.add_argument("--keep", action="store_true",
                        help="keep the temporary car directory")
    parser.add_argument("--web", action="store_true",
                        help="also start the mode/lane toggle page")
    parser.add_argument("--lane-port", type=int, default=8899,
                        help="port for the throwaway toggle page")
    parser.add_argument("--debug-overlay", action="store_true",
                        help="enable the CV debug overlay")
    args = parser.parse_args()
    sys.exit(main(args.controller, args.loops, args.keep, args.web_port,
                  {"web_enable": args.web, "lane_port": args.lane_port,
                   "debug": args.debug_overlay}))
